name: "Upload Image"
description: "Uploads the modified image."

inputs:
  image_path:
    description: "The path to the modified image."
    required: true
  release_id:
    description: "The release ID."
    required: true
  cache_key:
    description: "The cache key."
    required: true

runs:
  using: "composite"
  steps:
    - name: Upload to release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: ${{ inputs.image_path }}
          release_id: ${{ inputs.release_id }}
          draft: false
          overwrite: true
          prerelease: false
          verbose: true
