name: Modify RPi Image
description: Modify Raspberry Pi image
inputs:
  mycroft_config_files:
    description: "Mycroft configuration files"
    required: true
    default: "mycroft.conf,mycroft_en.conf"
  image_path:
    description: "Image path"
    required: true
    default: "raspOVOS-bookworm-arm64-lite.img"
  base-image-path: 
    description: "base image url"
    requered: true
    default: "https://github.com/${{ github.repository }}/releases/download/raspOVOS-bookworm-arm64-lite-${{ inputs.current_date }}/raspOVOS-bookworm-arm64-lite.img.xz"
  script-path: 
    description: "script-path"
    requered: true
    default: "build_raspOVOS.sh"
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Configuring OVOS for English
      uses: TigreGotico/rpi-image-modifier@main
      id: create-image
      env:
        USER: 'ovos'
        PASSWORD: 'ovos'
        HOSTNAME: "raspOVOS"
        CONSTRAINTS: "https://github.com/OpenVoiceOS/ovos-releases/raw/refs/heads/main/constraints-alpha.txt"
        MYCROFT_CONFIG_FILES: ${{ inputs.mycroft_config_files }}
      with:
        base-image-url: https://github.com/${{ github.repository }}/releases/download/raspOVOS-bookworm-arm64-lite-${{ inputs.current_date }}/raspOVOS-bookworm-arm64-lite.img.xz
        image-path: ${{ inputs.image_path }}
        compress-with-xz: true
        shrink: true
        cache: false
        mount-repository: true
        env-vars: USER,PASSWORD,HOSTNAME,CONSTRAINTS,MYCROFT_CONFIG_FILES
        script-path: build_raspOVOS_en.sh
    - name: Print outputs
      shell: bash
      run: |
        echo "image-path: ${{ steps.create-image.outputs.image-path }}"
        echo "image-size: ${{ steps.create-image.outputs.image-size }}"
        echo "image-sha256sum: ${{ steps.create-image.outputs.image-sha256sum }}"
    - name: Save Image to Cache
      uses: actions/cache@v4
      with:
        path: .
        key: ${{ inputs.cache_key }}
