name: "Modify RPi Image"
description: "Modifies the RPi image."

inputs:
  base-image-url:
    description: "The URL of the base image."
    required: true
  image-path:
    description: "The path to the image."
    required: true
  script-path:
    description: "The path to the script."
    required: true

outputs:
  image_path:
    description: "The path to the modified image."

runs:
  using: "composite"
  steps:
    - name: Modify RPi image
      id: modify-rpi-image
      steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Tune base Raspberry Pi OS Bookworm
        uses: TigreGotico/rpi-image-modifier@main
        id: create-image
        env:
          USER: 'ovos'
          PASSWORD: 'ovos'
          HOSTNAME: "raspOVOS"
        with:
          base-image-url: ${{ inputs.base-image-url }}
          image-path: ${{ inputs.image-path }} 
          compress-with-xz: true
          cache: false
          shrink: true
          mount-repository: true
          env-vars: USER,PASSWORD,HOSTNAME
          script-path: ${{ inputs.script-path }}
        shell: bash
        run: |
          echo "image-path=${{ steps.create-image.outputs.image-path }} >> $GITHUB_OUTPUT

      - name: Print outputs
        shell: bash
        run: |
          echo "image-path: ${{ steps.create-image.outputs.image-path }}"
          echo "image-size: ${{ steps.create-image.outputs.image-size }}"
          echo "image-sha256sum: ${{ steps.create-image.outputs.image-sha256sum }}"
    - name: Print outputs
      shell: bash
      run: |
        echo "image_path: ${{ steps.modify-rpi-image.outputs.image_path }}"