name: Build Base Image

on:
  workflow_dispatch:

jobs:
  get-date-release-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Date Release Name
        id: get-date-release-name
        uses: ./.github/actions/get_date_release_name
 
      - name: Check release or create
        id: check-release-or-create
        uses: ./.github/actions/check_release_or_create
        with:
          release_name: ${{ steps.get-date-release-name.outputs.release_name }}
          release_txt: "RaspOVOS multiple builds"
          GITHUB_TOKEN: ${{ secrets.PA_TOKEN }}

      - name: Modify RPi image
        id: build-base-image
        uses: ./.github/actions/modify_rpi_image
        with:
          base-image-url: https://downloads.raspberrypi.com/raspios_lite_arm64/images/raspios_lite_arm64-2024-11-19/2024-11-19-raspios-bookworm-arm64-lite.img.xz
          image-path: raspOVOS-NO-OVOS-bookworm-arm64-lite.img
          script-path: ./base/build_base.sh

      - name: Upload image
        id: upload-image
        uses: ./.github/actions/upload_image
        with:
          image_path: ${{ steps.build-base-image.outputs.image_path }}
          release_id: ${{ steps.check-release-or-create.outputs.release_id }}
          cache_key: ${{ steps.get-date-release-name.outputs.cache_key }}