name: Build Base Image

on:
  workflow_dispatch:

jobs:
  get-date-release-name:
    runs-on: ubuntu-latest
    steps:
      - name: Get Date Release Name
        id: get-date-release-name
        uses: ./.github/actions/get_date_release_name.yml
      
  check-release-or-create:
    needs: get-date-release-name
    runs-on: ubuntu-latest
    steps:
      - name: Check release or create
        id: check-release-or-create
        uses: ./.github/actions/check_release_or_create
        with:
          release_name: ${{ steps.get-date-release-name.outputs.release_name }}
          cache_key: ${{ steps.get-date-release-name.outputs.cache_key }}

  build-base-image:
    needs: [check-release-or-create, get-date-release-name]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Modify RPi image
        id: build-base-image
        uses: ./.github/actions/modify_rpi_image
        with:
          base-image-url: https://downloads.raspberrypi.com/raspios_lite_arm64/images/raspios_lite_arm64-2024-11-19/2024-11-19-raspios-bookworm-arm64-lite.img.xz
          release_name: ${{ needs.get-date-release-name.outputs.release_name }}
          script-path: ./base/build_base.sh


upload-image:
    needs: [build-base-image, check-release-or-create, get-date-release-name]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Upload image
        id: upload-image
        uses: ./.github/actions/upload_image
        with:
          image_path: ${{ needs.build-base-image.outputs.image_path }}
          release_id: ${{ needs.check-release-or-create.outputs.release_id }}
          cache_key: ${{ needs.get-date-release-name.outputs.cache_key }}