name: Build Headles Image

on:
  workflow_dispatch:
    inputs:
      base-image-url:
        description: "The URL of the base image."
        required: true
        type: string
      release_id:
        description: 'The release ID'
        required: true
        type: string
      cache_key:     
        description: 'The generated cache key'
        required: true
        type: string
      image-path:
        description: 'Name of the image to be created'
        required: true
        type: string

jobs:
  build-image:
    uses: ./.github/workflows/modify_rpi_image.yml
    with:
      base-image-url: https://downloads.raspberrypi.com/raspios_lite_arm64/images/raspios_lite_arm64-2024-11-19/2024-11-19-raspios-bookworm-arm64-lite.img.xz
      release_id: ${{ needs.create-release.outputs.release_id }}
      cache_key: ${{ needs.create-release.outputs.cache_key }}
      image-path: raspOVOS-NO-OVOS-bookworm-arm64-lite.img
      mycroft-config-files: mycroft.conf
      script-path: ./base/build_base.sh