name: Build Base Image 1

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/build_base.yml'
      - 'build_base.sh'
      - 'tuning/**'
      - 'services/kdeconnect.service'
      - 'services/wlan0-power.service'
      - 'packages/setup_pipewire.sh'
      - 'packages/setup_kdeconnect.sh'
      - 'packages/setup_balena_wifi.sh'
      - 'packages/wifi-connect/**'
      - 'packages/wifi-connect.bin'
      - 'patches/firstboot'
      - 'patches/userconf'
      - 'patches/boot_config.txt'

jobs:
  get-date-release-name:
    uses: ./.github/workflows/get_date_release_name.yml

  modify-rpi-image:
    needs: get-date-release-name
    run: |
      release_name=${{ needs.get-date-release-name.outputs.release_name }}
      cache_key=${{ needs.get-date-release-name.outputs.cache_key }}
      ./.github/workflows/modify_rpi_image.yml --release-name $release_name --cache-key $cache_key

  check-release-or-create:
    needs: [get-date-release-name, modify-rpi-image]
    uses: ./.github/workflows/check_release_or_create.yml
    with:
      release_name: ${{ jobs.get-date-release-name.outputs.release_name }}

