name: Build Release

on:
  workflow_dispatch:

env:
  mycroft-conig-path: ./mycroft-configs
  language: en-us

jobs:
  create-release:
    uses: ./.github/workflows/create_release.yml
    with:
      base_name: raspOVOS-bookworm-arm64-lite
      base_txt: |
        Raspberry Pi OS Bookworm Lite with OpenVoiceOS modifications
        raspOVOS-NO-OVOS-bookworm-arm64-lite.img - Base image with no OVOS
        raspOVOS-bookworm-arm64-lite.img - raspOVOS with OVOS
        raspOVOS-GUI-bookworm-arm64-lite.img - raspOVOS with OVOS and GUI
        raspOVOS-mark2-bookworm-arm64-lite.img - raspOVOS with OVOS and GUI for the Mark2

  build-base-image:
    needs: create-release
    uses: ./.github/workflows/modify_rpi_image.yml
    with:
      base-image-url: https://downloads.raspberrypi.com/raspios_lite_arm64/images/raspios_lite_arm64-2024-11-19/2024-11-19-raspios-bookworm-arm64-lite.img.xz
      release_url: ${{ needs.create-release.outputs.release_url }}
      release_id: ${{ needs.create-release.outputs.release_id }}
      cache_key: ${{ needs.create-release.outputs.cache_key }}
      image-path: raspOVOS-NO-OVOS-bookworm-arm64-lite.img
      mycroft-config-files: mycroft.conf
      script-path: build_base.sh
      
  build-headles-image:
    needs: [create-release, build-base-image]
    uses: ./.github/workflows/modify_rpi_image.yml
    with:
      base-image-url: ${{ needs.build-base-image.outputs.image-url}} 
      release_url: ${{ needs.create-release.outputs.release_url }}
      release_id: ${{ needs.create-release.outputs.release_id }}
      cache_key: ${{ needs.create-release.outputs.cache_key }}
      image-path: raspOVOS-bookworm-arm64-lite.img
      mycroft-config-files: mycroft.conf
      script-path: build_raspOVOS.sh

  build-gui-image:
    needs: [create-release, build-base-image, build-headles-image]
    uses: ./.github/workflows/modify_rpi_image.yml
    with:
      base-image-url: ${{ needs.build-headles-image.outputs.image-url }}
      release_url: ${{ needs.create-release.outputs.release_url }}
      release_id: ${{ needs.create-release.outputs.release_id }}
      cache_key: ${{ needs.create-release.outputs.cache_key }}
      image-path: raspOVOS-GUI-bookworm-arm64-lite.img
      mycroft-config-files: mycroft.conf, mycroft-gui.conf
      script-path: build_raspOVOS_gui.sh
        
  build-mk2-image:
    needs: [create-release, build-base-image, build-headles-image, build-gui-image]
    uses: ./.github/workflows/modify_rpi_image.yml
    with:
      base-image-url: ${{ needs.build-gui-image.outputs.image-url }}
      release_url: ${{ needs.create-release.outputs.release_url }}
      release_id: ${{ needs.create-release.outputs.release_id }}
      cache_key: ${{ needs.create-release.outputs.cache_key }}
      image-path: raspOVOS-mark2-bookworm-arm64-lite.img
      mycroft-config-files: mycroft.conf, mycroft-gui.conf
      script-path: build_raspOVOS_mk2.sh