name: Build Base Image

on:
  workflow_dispatch:

jobs:
  get-date-release-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get date release name
        id: get-date-release-name
        uses: ./.github/workflows/get_date_release_name.yml

  check-release-or-create:
    needs: get-date-release-name
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check release or create
        id: check-release-or-create
        uses: ./.github/workflows/check_release_or_create.yml

  build-base-image:
    needs: [check-release-or-create, get-date-release-name]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Modify RPi image
        id: build-base-image
        uses: ./.github/workflows/modify_rpi_image.yml
        with:
          base-image-url: https://downloads.raspberrypi.com/raspios_lite_arm64/images/raspios_lite_arm64-2024-11-19/2024-11-19-raspios-bookworm-arm64-lite.img.xz
          release_name: raspOVOS-NO-OVOS-bookworm-arm64-lite.img
          script-path: ./base/build_base.sh

  upload-image:
    needs: [build-base-image, check-release-or-create, get-date-release-name]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Upload image
        id: upload-image
        uses: ./.github/workflows/upload_image.yml
        with:
          image_path: ${{ steps.build-base-image.outputs.image_path }}
          release_id: ${{ steps.check-release-or-create.outputs.release_id }}
          cache_key: ${{ steps.check-release-or-create.outputs.cache_key }}