# This reusable workflow builds images for different languages.
# It performs the following steps:
# 1. Accepts inputs for the base image URL, release URL, release ID, cache key, Mycroft configuration files, script path, and languages.
# 2. Calls the modify_rpi_image.yml workflow to build headless images for each specified language.
# 3. Calls the modify_rpi_image.yml workflow to build GUI images for each specified language.
# 4. Calls the modify_rpi_image.yml workflow to build Mark II images for each specified language.
# 5. Outputs the image URL for each image.

name: Build Images

on:
  workflow_call:
    inputs:
      base_image_url:
        description: 'The URL of the base image'
        required: true
        type: string
      release_url:
        description: 'The release URL'
        required: true
        type: string
      release_id:
        description: 'The release ID'
        required: true
        type: string
      cache_key:
        description: 'The cache key'
        required: true
        type: string
      languages:
        description: 'The languages'
        required: true
        type: string 
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug - Print Input Variables
        run: |
          echo "base-image-url: ${{ inputs.base_image_url }}"
          echo "release_url: ${{ inputs.release_url }}"
          echo "release_id: ${{ inputs.release_id }}"
          echo "cache_key: ${{ inputs.cache_key }}"
          echo "image-path: raspOVOS-${{ inputs.languages }}-bookworm-arm64-lite.img"
          echo "mycroft-config-files: ${{ inputs.mycroft_config_files }}"
          echo "script-path: ${{ inputs.script_path }}"
          echo "constraints: ${{ inputs.constraints }}"
          echo "languages: ${{ inputs.languages }}"

  build-headles-image:
    uses: ./.github/workflows/modify_rpi_image.yml
    with:
      base_image_url: ${{ inputs.base_image_url }}
      release_url: ${{ inputs.release_url}}
      release_id: ${{ inputs.release_id }}
      cache_key: ${{ inputs.cache_key }}
      image_path: "raspOVOS-${{ inputs.languages }}-bookworm-arm64-lite.img"
      mycroft_config_files: "./languages/default/mycroft.conf,./languages/${{ inputs.languages }}/mycroft.conf" 
      script_path: ./languages/${{ inputs.languages }}/build_raspOVOS.sh 
      constraints: https://github.com/OpenVoiceOS/ovos-releases/raw/refs/heads/main/constraints-alpha.txt

  build-gui-image:
    needs: [build-headles-image]
    uses: ./.github/workflows/modify_rpi_image.yml
    with:
      base_image_url: ${{ needs.build-headles-image.outputs.image_url }}
      release_url: ${{ inputs.release_url}}
      release_id: ${{ inputs.release_id }}
      cache_key: ${{ inputs.cache_key }}
      image_path: "raspOVOS-${{ inputs.languages }}-GUI-bookworm-arm64-lite.img"
      mycroft_config_files: "./languages/default/mycroft.conf,.languages/default/mycroft_gui.conf,./languages/${{ inputs.languages }}/mycroft.conf,./languages/${{ inputs.languages }}/mycroft_gui.conf" 
      script_path: ./languages/${{ inputs.languages }}/build_raspOVOS_gui.sh 
      constraints: https://github.com/OpenVoiceOS/ovos-releases/raw/refs/heads/main/constraints-alpha.txt
        
#  build-mk2-image:
#    needs: [create-release, build-base-image, build-headles-image, build-gui-image]
#    uses: ./.github/workflows/modify_rpi_image.yml
#    with:
#      base-image-url: ${{ needs.build-gui-image.outputs.image-url }}
#      release_url: ${{ needs.create-release.outputs.release_url }}
#      release_id: ${{ needs.create-release.outputs.release_id }}
#      cache_key: ${{ needs.create-release.outputs.cache_key }}
#      image-path: raspOVOS-mark2-bookworm-arm64-lite.img
#      mycroft-config-files: mycroft.conf, mycroft_gui.conf
#      script-path: build_raspOVOS_mk2.sh
