name: Check if Release Exists and Create if Needed

on:
  workflow_call:
    inputs:
      release_name:
        required: true
    outputs:
      release_id:
        description: 'ID of the created or existing release'

jobs:
  check-release-or-create:
    runs-on: ubuntu-latest
    steps:
      - name: Check if Release Exists
        id: get-release-id
        run: |
          release_name="${{ inputs.release_name }}"
          release=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/tags/$release_name")
          release_id=$(echo $release | jq -r .id)
          if [[ "$release_id" == "null" ]]; then
            release=$(curl -s -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Content-Type: application/json" \
              -d "{\"tag_name\":\"$release_name\",\"name\":\"$release_name\",\"body\":\"Testing base OS setup only.\"}" \
              "https://api.github.com/repos/${{ github.repository }}/releases")
            release_id=$(echo $release | jq -r .id)
          fi
          echo "release_id=$release_id" >> $GITHUB_OUTPUT

      - name: Print outputs
        shell: bash
        run: |
          echo "release_id: ${{ steps.get-release-id.outputs.release_id }}"
          if [[ $release_id == "null" ]]; then
            echo "Failed to create release. Response: $release"
            exit 1
        outputs:
          release_id: ${{ steps.get-release-id.outputs.release_id }}
