name: Get Current Date and Release Name

on:
  workflow_call:
    inputs:
      release_name:
        required: true
        type: string
      cache_key:
        required: true
        type: string
    outputs:
      release_name:
        description: 'The generated release name'
        value: ${{ jobs.get-date-release-name.outputs.release_name }}
      cache_key:
        description: 'The generated cache key'
        value: ${{ jobs.get-date-release-name.outputs.cache_key }}

jobs:
  get-date-release-name:
    runs-on: ubuntu-latest
    outputs:
      release_name: ${{ steps.current-date.outputs.release_name }}
      cache_key: ${{ steps.current-date.outputs.cache_key }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Get Current Date and Release Name
        id: current-date
        run: |
          current_date=$(date +'%Y-%m-%d')
          release_name="raspOVOS-bookworm-arm64-lite-${current_date}"
          cache_key="raspOVOS-${{ github.run_id }}"
          echo "release_name=$release_name" >> $GITHUB_OUTPUT
          echo "cache_key=$cache_key" >> $GITHUB_OUTPUT

      - name: Print outputs
        shell: bash
        run: |
          echo "cache_key: ${{ steps.current-date.outputs.cache_key }}"
          echo "release_name: ${{ steps.current-date.outputs.release_name }}"