name: Get Current Date and Release Name

on:
  workflow_call:
    outputs:
      release_name:
        description: 'The generated release name'
      cache_key:
        description: 'The generated cache key'

jobs:
  get-date-release-name:
    runs-on: ubuntu-latest
    steps:
      - name: Get Current Date and Release Name
        id: current-date
        run: |
          current_date=$(date +'%Y-%m-%d')
          release_name="raspOVOS-NO-OVOS-bookworm-arm64-lite-${current_date}"
          cache_key="raspOVOS-${{ github.run_id }}"
          echo "release_name=$release_name" >> $GITHUB_OUTPUT
          echo "cache_key=$cache_key" >> $GITHUB_OUTPUT

      - name: Print outputs
        shell: bash
        run: |
          echo "cache_key: ${{ steps.current-date.outputs.cache_key }}"
          echo "release_name: ${{ steps.current-date.outputs.release_name }}"
