# This reusable workflow modifies a Raspberry Pi OS image.
# It performs the following steps:
# 1. Checks out the repository.
# 2. Checks if the image is already uploaded to GitHub.
# 3. Tunes the base Raspberry Pi OS Bookworm image using the TigreGotico/rpi-image-modifier action.
# 4. Prints the outputs, including the image path, image size, and image sha256sum.
# 5. Uploads the modified image to a GitHub release.

name: Modify RPi Image

on:
  workflow_call:
    inputs:
      base-image-url:
        description: 'The URL of the base image'
        required: true
        type: string
      release_id:
        description: 'The release ID'
        required: true
        type: string
      cache_key:
        description: 'The cache key'
        required: true
        type: string
      image-path:
        description: 'The path to the modified image'
        required: true
        type: string
      script-path:
        description: 'The path to the script'
        required: true
        type: string
      mycroft-config-files:
        description: 'The Mycroft configuration files'
        required: true
        type: string
    outputs:
      image-path:
        description: 'The path to the modified image'
        value: ${{ jobs.modify-rpi-image.outputs.image-path }}
      image-size:
        description: 'The size of the modified image'
        value: ${{ jobs.modify-rpi-image.outputs.image-size }}
      image-sha256sum:
        description: 'The sha256sum of the modified image'
        value: ${{ jobs.modify-rpi-image.outputs.image-sha256sum }}
jobs:
  modify-rpi-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if Image is Already Uploaded
        id: check-image
        run: |
          image_url="https://github.com/${{ github.repository }}/releases/download/${{ inputs.release_id }}/${{ inputs.image-path }}"
          response=$(curl --write-out '%{http_code}' --silent --output /dev/null "$image_url")
          if [ "$response" -eq 200 ]; then
            echo "Image already exists at $image_url"
            echo "skip_create_image=true" >> $GITHUB_ENV
            echo "image_url=$image_url" >> $GITHUB_ENV
          else
            echo "Image does not exist at $image_url"
            echo "skip_create_image=false" >> $GITHUB_ENV

      - name: Tune base Raspberry Pi OS Bookworm
        if: ${{ steps.check-image.outputs.skip_create_image == 'false' }}
        uses: TigreGotico/rpi-image-modifier@main
        id: create-image
        env:
          USER: 'ovos'
          PASSWORD: 'ovos'
          HOSTNAME: "raspOVOS"
          CONSTRAINTS: "https://github.com/OpenVoiceOS/ovos-releases/raw/refs/heads/main/constraints-alpha.txt"
          MYCROFT_CONFIG_FILES: ${{ inputs.mycroft-config-files }}
        with:
          base-image-url: ${{ inputs.base-image-url }}
          image-path: ${{ inputs.image-path }}
          compress-with-xz: true
          cache: false
          shrink: true
          mount-repository: true
          env-vars: USER,PASSWORD,HOSTNAME,CONSTRAINTS,MYCROFT_CONFIG_FILES
          script-path: ${{ inputs.script-path }}

      - name: Print outputs
        shell: bash
        run: |
          echo "image-path: ${{ steps.create-image.outputs.image_path }}"
          echo "image-size: ${{ steps.create-image.outputs.image_size }}"
          echo "image-sha256sum: ${{ steps.create-image.outputs.image_sha256sum }}"

      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.set-output-image-path.outputs.image_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}