# This reusable workflow modifies a Raspberry Pi OS image.
# It performs the following steps:
# 1. Checks out the repository.
# 2. Checks if the image is already uploaded to GitHub.
# 3. Tunes the base Raspberry Pi OS Bookworm image using the TigreGotico/rpi-image-modifier action.
# 4. Prints the outputs, including the image path, image size, and image sha256sum.
# 5. Uploads the modified image to a GitHub release.

name: Modify RPi Image

on:
  workflow_call:
    inputs:
      base_image_url:
        description: 'The URL of the base image'
        required: true
        type: string
      release_id:
        description: 'The release ID'
        required: true
        type: string
      release_url:
        description: 'The release URL'
        required: true
        type: string
      cache_key:
        description: 'The cache key'
        required: true
        type: string
      image_path:
        description: 'The path to the modified image'
        required: true
        type: string
      script_path:
        description: 'The path to the script'
        required: true
        type: string
      mycroft_config_files:
        description: 'The Mycroft configuration files'
        required: false
        type: string
      constraints:
        description: 'The constraints file'
        required: false
        type: string
    outputs:
      image_path:
        description: 'The path to the modified image'
        value: ${{ jobs.modify-rpi-image.outputs.image-path }}
      image_url:
        description: 'The URL of the modified image'
        value: ${{ jobs.modify-rpi-image.outputs.image-url }}
      image_size:
        description: 'The size of the modified image'
        value: ${{ jobs.modify-rpi-image.outputs.image-size }}
      image_sha256sum:
        description: 'The sha256sum of the modified image'
        value: ${{ jobs.modify-rpi-image.outputs.image-sha256sum }}
jobs:
  modify-rpi-image:
    runs-on: ubuntu-latest
    outputs:
      image-path: ${{ steps.create-image.outputs.image-path }}
      image-url: ${{ steps.image-url-path.outputs.image-url }}
      image-size: ${{ steps.create-image.outputs.image-size }}
      image-sha256sum: ${{ steps.create-image.outputs.image-sha256sum }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Debug - Print Input Variables
        run: |
          echo "base_image_url: ${{ inputs.base_image_url }}"
          echo "release_id: ${{ inputs.release_id }}"
          echo "release_url: ${{ inputs.release_url }}"
          echo "cache_key: ${{ inputs.cache_key }}"
          echo "image_path: ${{ inputs.image_path }}"
          echo "script_path: ${{ inputs.script_path }}"
          echo "mycroft_config_files: ${{ inputs.mycroft_config_files }}"
          echo "constraints: ${{ inputs.constraints }}"

      - name: Check if Required Files Exist
        id: check-files
        run: |
          if [ ! -f "${{ inputs.script_path }}" ]; then
            echo "Script file ${{ inputs.script_path }} does not exist."
            echo "skip_steps=true" >> $GITHUB_OUTPUT
            echo "Script file ${{ inputs.script_path }} exist."
          else
            IFS=',' read -r -a file_array <<< "${{ inputs.mycroft_config_files }}"
            for config_file in "${file_array[@]}"; do
              if [ ! -f "$config_file" ]; then
                echo "Mycroft config file $config_file does not exist."
                echo "skip_steps=true" >> $GITHUB_OUTPUT
                exit 0
              fi
            done
            echo "skip_steps=false" >> $GITHUB_OUTPUT
          fi
      - name: Check if Base Image URL Ends with .xz
        id: check-base-image-url
        run: |
          base_image_url="${{ inputs.base_image_url }}"
          if [[ "$base_image_url" != *.xz ]]; then
            base_image_url="${base_image_url}.xz"
          fi
          echo "base_image_url=$base_image_url" >> $GITHUB_OUTPUT

      - name: Check if Image is Already Uploaded
        id: check-image
        run: |
          image_url=${{ inputs.release_url }}/${{ inputs.image_path }}.xz
          echo "Checking URL: $image_url"
          response=$(curl -L --write-out '%{http_code}' --silent --output /dev/null "$image_url")
          if [ "$response" -eq 200 ]; then
            echo "Image already exists at $image_url"
            echo "skip_create_image=true" >> $GITHUB_OUTPUT
            echo "image_url=$image_url" >> $GITHUB_OUTPUT
            echo "image_path=${{ inputs.image_path }}.xz" >> $GITHUB_OUTPUT
          else
            echo "Image does not exist at $image_url"
            echo "skip_create_image=false" >> $GITHUB_OUTPUT
          fi

      - name: Tune base Raspberry Pi OS Bookworm
        if: ${{ steps.check-files.outputs.skip_steps == 'false' && steps.check-image.outputs.skip_create_image == 'false' }}
        uses: TigreGotico/rpi-image-modifier@main
        id: create-image
        env:
          USER: 'ovos'
          PASSWORD: 'ovos'
          HOSTNAME: "raspOVOS"
          CONSTRAINTS: ${{ inputs.constraints }} 
          MYCROFT_CONFIG_FILES: ${{ inputs.mycroft_config_files }}
        with:
          base-image-url: ${{ inputs.base_image_url }}
          image-path: ${{ inputs.image_path }}
          compress-with-xz: true
          cache: false
          shrink: true
          mount-repository: true
          env-vars: USER,PASSWORD,HOSTNAME,CONSTRAINTS,MYCROFT_CONFIG_FILES
          script-path: ${{ inputs.script_path }}
  
      - name: Set output image URL and path
        if: ${{ steps.check-image.outputs.skip_create_image == 'true' }}
        id: image-url-path
        run: |
          echo "image-url=${{ inputs.release_url }}/${{ inputs.image_path }}.xz" >> $GITHUB_OUTPUT
          echo "image-path=${{ inputs.image_path }}.xz" >> $GITHUB_OUTPUT

      - name: Print outputs
        shell: bash
        run: |
          echo "image-path: ${{ steps.create-image.outputs.image-path }}"
          echo "image-size: ${{ steps.create-image.outputs.image-size }}"
          echo "image-sha256sum: ${{ steps.create-image.outputs.image-sha256sum }}"

      - name: Upload to release
        if: ${{ steps.check-files.outputs.skip_steps == 'false' && steps.check-image.outputs.skip_create_image == 'false' }}
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: ${{ steps.create-image.outputs.image-path }}
          release_id: ${{ inputs.release_id }}
          draft: false
          overwrite: true
          prerelease: false
          verbose: true
        