name: Modify RPI Image

on:
  workflow_call:
    inputs:
      image-path:
        description: 'Name of the image to be created'
        required: true
        type: string
      base-image-url:
        description: "The URL of the base image."
        required: true
        type: string
      release_id:
        description: 'The release ID'
        required: true
        type: string
      script-path:
        description: 'The path to the script to be executed'
        required: true
        type: string
      mycroft-config-files:
        description: 'Mycroft configuration files'
        required: true
        default: "mycroft.conf"
        type: string
      cache_key:
        description: 'The generated cache key'
        required: true
        type: string
jobs:
  modify-rpi-image:
    runs-on: ubuntu-latest
    outputs:
      image-path: ${{ steps.create-image.outputs.image-path }}
      image-size: ${{ steps.create-image.outputs.image-size }}
      image-sha256sum: ${{ steps.create-image.outputs.image-sha256sum }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Tune base Raspberry Pi OS Bookworm
        uses: TigreGotico/rpi-image-modifier@main
        id: create-image
        env:
          USER: 'ovos'
          PASSWORD: 'ovos'
          HOSTNAME: "raspOVOS"
          CONSTRAINTS: "https://github.com/OpenVoiceOS/ovos-releases/raw/refs/heads/main/constraints-alpha.txt"
          MYCROFT_CONFIG_FILES: ${{ inputs.mycroft-config-files }}

        with:
          base-image-url: ${{ inputs.base-image-url }} 
          image-path: ${{ inputs.image-path }}
          compress-with-xz: true
          cache: false
          shrink: true
          mount-repository: true
          env-vars: USER,PASSWORD,HOSTNAME
          script-path: ${{ inputs.script-path }}

      - name: Print outputs
        shell: bash
        run: |
          echo "image-path: ${{ steps.create-image.outputs.image-path }}"
          echo "image-size: ${{ steps.create-image.outputs.image-size }}"
          echo "image-sha256sum: ${{ steps.create-image.outputs.image-sha256sum }}"

      - name: Save Image to Cache
        uses: actions/cache@v4
        with:
          path: .
          key: ${{ inputs.cache_key }}

  upload-to-release:
    runs-on: ubuntu-latest
    needs: [modify-rpi-image]
    steps:
      - name: Upload to release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PA_TOKEN }}
        with:
          file: ${{ needs.modify-rpi-image.outputs.image-path }}
          release_id: ${{ inputs.release_id }}
          draft: false
          overwrite: true
          prerelease: false
          verbose: true