# This reusable workflow modifies a Raspberry Pi OS image.
# It performs the following steps:
# 1. Checks out the repository.
# 2. Checks if the image is already uploaded to GitHub.
# 3. Tunes the base Raspberry Pi OS Bookworm image using the TigreGotico/rpi-image-modifier action.
# 4. Prints the outputs, including the image path, image size, and image sha256sum.
# 5. Uploads the modified image to a GitHub release.

name: Modify RPi Image

on:
  workflow_call:
    inputs:
      base_image_url:
        description: 'The URL of the base image'
        required: true
        type: string
      release_id:
        description: 'The release ID'
        required: true
        type: string
      release_url:
        description: 'The release URL'
        required: true
        type: string
      cache_key:
        description: 'The cache key'
        required: true
        type: string
      image_path:
        description: 'The path to the modified image'
        required: true
        type: string
      script_path:
        description: 'The path to the script'
        required: true
        type: string
      mycroft_config_files:
        description: 'The Mycroft configuration files'
        required: false
        type: string
      constraints:
        description: 'The constraints file'
        required: false
        type: string
      intent_cache:
        description: 'The intent cache'
        required: false
        type: string
      update-image:
        description: 'Forse updating image'
        required: false
        type: boolean
    outputs:
      image_path:
        description: 'The path to the modified image'
        value: ${{ jobs.modify-rpi-image.outputs.image_path }}
      image_url:
        description: 'The URL of the modified image'
        value: ${{ jobs.modify-rpi-image.outputs.image_url }}
      image_size:
        description: 'The size of the modified image'
        value: ${{ jobs.modify-rpi-image.outputs.image_size }}
      image_sha256sum:
        description: 'The sha256sum of the modified image'
        value: ${{ jobs.modify-rpi-image.outputs.image_sha256sum }}
jobs:
  modify-rpi-image:
    name: Make ${{ inputs.image_path }}
    runs-on: ubuntu-latest
    outputs:
      image_path: ${{ steps.output-variables.outputs.image_path }}
      image_url: ${{ steps.output-variables.outputs.image_url }}
      image_size: ${{ steps.create-image.outputs.image-size }}
      image_sha256sum: ${{ steps.create-image.outputs.image-sha256sum }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Check if Required Files Exist
        id: check-files
        run: |
          if [ ! -f "${{ inputs.script_path }}" ]; then
            echo "Script file ${{ inputs.script_path }} does not exist."
            echo "skip_steps=true" >> $GITHUB_OUTPUT
          else
            echo "skip_steps=false" >> $GITHUB_OUTPUT
            echo "Script file ${{ inputs.script_path }} exist."
          fi

      - name: Check if Base Image URL Ends with .xz
        id: check-base-image-url
        run: |
          base_image_url="${{ inputs.base_image_url }}"
          if [[ "$base_image_url" != *.xz ]]; then
            base_image_url="${base_image_url}.xz"
          fi
          echo "base_image_url=$base_image_url" >> $GITHUB_OUTPUT
          echo "base_image_url=$base_image_url"

      - name: Check if Image is Already Uploaded
        id: check-image
        run: |
          image_url=${{ inputs.release_url }}/${{ inputs.image_path }}.xz
          echo "Checking URL: $image_url"
          response=$(curl -L --write-out '%{http_code}' --silent --output /dev/null "$image_url")
          if [ "$response" -eq 200 ]; then
            echo "Image already exists at $image_url"
            echo "skip_create_image=true" >> $GITHUB_OUTPUT
            echo "image_url=$image_url" >> $GITHUB_OUTPUT
            echo "image_path=${{ inputs.image_path }}.xz" >> $GITHUB_OUTPUT
            echo "image_url=${{ inputs.release_url }}/${{ inputs.image_path }}.xz" >> $GITHUB_OUTPUT
          else
            echo "Image does not exist at $image_url"
            echo "skip_create_image=false" >> $GITHUB_OUTPUT
          fi
          if [ "${{ inputs.update-image }}" == "true" ]; then
            echo "skip_create_image=false" >> $GITHUB_OUTPUT
          fi

      - name: Modify base image
        if: ${{ steps.check-files.outputs.skip_steps == 'false' && steps.check-image.outputs.skip_create_image == 'false' }}
        uses: TigreGotico/rpi-image-modifier@main
        id: create-image
        env:
          USER: 'ovos'
          PASSWORD: 'ovos'
          HOSTNAME: "raspOVOS"
          CONSTRAINTS: ${{ inputs.constraints }} 
          MYCROFT_CONFIG_FILES: ${{ inputs.mycroft_config_files }}
          IMTENT_CACHE: ${{ inputs.intent_cache }}
        with:
          base-image-url: ${{ steps.check-base-image-url.outputs.base_image_url }}
          image-path: ${{ inputs.image_path }}
          compress-with-xz: true
          cache: false
          shrink: true
          mount-repository: true
          env-vars: USER,PASSWORD,HOSTNAME,CONSTRAINTS,MYCROFT_CONFIG_FILES
          script-path: ${{ inputs.script_path }}

      - name: Output Variables
        id: output-variables
        run: |
          if [ "${{ steps.create-image.outputs.image-path }}" == "" ]; then
            echo "image_path= ${{ inputs.image_path }}" >> $GITHUB_OUTPUT
            echo "image_url=${{ inputs.release_url }}/${{ inputs.image_path }}.xz" >> $GITHUB_OUTPUT
          else
            echo "image_path=${{ steps.create-image.outputs.image-path }}" >> $GITHUB_OUTPUT
            echo "image_url=${{ inputs.release_url }}/${{ steps.create-image.outputs.image-path }}" >> $GITHUB_OUTPUT
          fi
  
      - name: Upload to release
        if: ${{steps.create-image.outputs.image-path != ''}}  
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: ${{ steps.create-image.outputs.image-path }}
          release_id: ${{ inputs.release_id }}
          draft: false
          overwrite: true
          prerelease: false
          verbose: true
