name: Modify Raspberry Pi Image

on:
  workflow_call:
    inputs:
      release_name:
        required: true
        type: string
      cache_key:
        required: true
        type: string
      base-image-url: 
        required: true
        type: string
      image-path:
        required: true
        type: string
      script-path:
        required: true
        type: string

    outputs:
      image_path:
        description: 'Path of the created image'
        value: ${{ jobs.modify-rpi-image.outputs.image_path }}

jobs:
  modify-rpi-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Tune base Raspberry Pi OS Bookworm
        uses: TigreGotico/rpi-image-modifier@main
        id: create-image
        env:
          USER: 'ovos'
          PASSWORD: 'ovos'
          HOSTNAME: "raspOVOS"
        with:
          base-image-url: ${{ inputs.base-image-url }}
          image-path: ${{ inputs.image-path }}
          compress-with-xz: true
          cache: false
          shrink: true
          mount-repository: true
          env-vars: USER,PASSWORD,HOSTNAME
          script-path: ${{ inputs.script-path }}

      - name: Print outputs
        shell: bash
        run: |
          echo "image-path: ${{ steps.create-image.outputs.image-path }}"
          echo "image-size: ${{ steps.create-image.outputs.image-size }}"
          echo "image-sha256sum: ${{ steps.create-image.outputs.image-sha256sum }}"
          echo "image-md5sum: ${{ steps.create-image.outputs.image-md5sum }}"
      - name: Save Image to Cache
        uses: actions/cache@v4
        with:
          path: .
          key: ${{ inputs.cache_key }}
