name: Upload to Release

on:
  workflow_call:
    inputs:
      image_path:
        required: true
        type: string
      release_id:
        required: true
        type: string
      cache_key:
        required: true
        type: string

jobs:
  upload-image:
    runs-on: ubuntu-latest
    steps:
      - name: Restore Cache for Image
        uses: actions/cache@v4
        with:
          path: .
          key: ${{ inputs.cache_key }}
          fail-on-cache-miss: true

      - name: Debug Cache Content
        run: ls .

      - name: Upload to release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: ${{ inputs.image_path }}
          release_id: ${{ inputs.release_id }}
          draft: false
          overwrite: true
          prerelease: false
          verbose: true
